### ISSUE TITLE
Blank page after deleting all text in the text box

### ISSUE THREAD

**Issue by leftiness** [mermaidjs/mermaid-live-editor#1]
**Steps to reproduce:**

1. Open the [Mermaid live editor][editor]
2. Delete all text in the text box

**Outcome:**

- Blank page. No text box. No page header. Nothing. React root is empty.

**Expectation:**

- The chart should be empty, but the rest of the editor should remain.

**Notes:**

- Tested in Firefox 54.0 and Chromium 56.0.2924.76 on Ubuntu 16.04

[editor]: https://mermaidjs.github.io/mermaid-live-editor

**Comment by tylerlong** [comment]
Fixed. Thanks.
