### ISSUE TITLE
Support styling classes

### ISSUE THREAD

**Issue by joostas** [mermaidjs/mermaid-live-editor#10]
ClassDef and class doesn't change style of elements. See example below:

graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[Car]

style A fill:#f00
classDef def fill: #f00
class B def

Style changes fill color of A element.
But assignment of class def to element B doesn't change fill color of B.

**Comment by tylerlong** [comment]
I confirm that `classDef` of mermaid 7.1.0 is broken.

**Comment by tylerlong** [comment]
Fixed.
