### ISSUE TITLE
Support mermaid configuration in the live-editor

### ISSUE THREAD

**Issue by agusmba** [mermaidjs/mermaid-live-editor#11]
I just asked for something similar in the cli project.

I'm not sure if the live editor depends on the cli or just on mermaidjs.

Be that as it may, it would be great being able to configure mermaid in the live editor, either by pasting the config json in another textbox, or integrating it with the diagram text.

Thanks!

**Comment by tylerlong** [comment]
It's a good idea and I have the plan to implement it in the near future.

**Comment by tylerlong** [comment]
Done.
