### ISSUE TITLE
Style of node label in flowchart has no font-size

### ISSUE THREAD

**Issue by yosshy** [mermaidjs/mermaid-live-editor#15]
I found a problem about downloaded SVGs of flowcharts. When I clicked "Link to view", they are displayed perfectly. But when I downloaded a SVG file via "Download SVG" and displayed it, they have no style about font size, so node labels are too long.

**Comment by tylerlong** [comment]
Could you please provide me with a sample flowchart?

**Comment by tylerlong** [comment]
Close as lack of feedback. Feel free to create a new issue.
