### ISSUE TITLE
gantt chart no longer working on live editor

### ISSUE THREAD

**Issue by pthieu** [mermaidjs/mermaid-live-editor#16]
I have some code for a gantt chart that I update periodically. Over the holiday, an update must have broken compatibility, because all the dates seem to be squished together.

Copying and pasting the gantt example from https://mermaidjs.github.io/gantt.html will reproduce the error. You can see it here: https://mermaidjs.github.io/mermaid-live-editor/#/edit/Z2FudHQKICAgIHRpdGxlIEEgR2FudHQgRGlhZ3JhbQogICAgZGF0ZUZvcm1hdCAgWVlZWS1NTS1ERAogICAgc2VjdGlvbiBTZWN0aW9uCiAgICBBIHRhc2sgICAgICAgICAgIDphMSwgMjAxNC0wMS0wMSwgMzBkCiAgICBBbm90aGVyIHRhc2sgICAgIDphZnRlciBhMSAgLCAyMGQKICAgIHNlY3Rpb24gQW5vdGhlcgogICAgVGFzayBpbiBzZWMgICAgICA6MjAxNC0wMS0xMiAgLCAxMmQKICAgIGFub3RoZXIgdGFzayAgICAgIDogMjRk

**Comment by tylerlong** [comment]
Confirmed. I can reproduce the issue.

**Comment by tylerlong** [comment]
Fixed.
