### ISSUE TITLE
index.html does not show anything

### ISSUE THREAD

**Issue by iwittkau** [mermaidjs/mermaid-live-editor#17]
I saw the [comment](https://github.com/mermaidjs/mermaid-live-editor/issues/8#issuecomment-331771705) in the dockerfile discussion  (#8), so I cloned the master branch into my local nginx html folder:

Firefox shows a blank page with the console output:

```
09:55:05.312 SyntaxError: import declarations may only appear at top level of a module index.js:1
```

Chrome fails with:

```
index.js:1 Uncaught SyntaxError: Unexpected identifier
```

Tried it with [http-server](https://www.npmjs.com/package/http-server), same result. Opening the `index.html` directly, same result.

---
OS: macOS 10.13.2 (17C205)
FF: 57.0.4 (64-Bit)
Chrome: 63.0.3239.132 (official build) (64-Bit)

**Comment by tylerlong** [comment]
Please open `docs/index.html` instead.  `./index.html` is for development only.
