### ISSUE TITLE
Notes in sequence diagram is not working

### ISSUE THREAD

**Issue by davojta** [mermaidjs/mermaid-live-editor#21]
Example from documentation: 
```
sequenceDiagram
    Alice ->> Bob: Hello Bob, how are you?
    Bob-->>John: How about you John?
    Bob--x Alice: I am good thanks!
    Bob-x John: I am good thanks!
    Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

    Bob-->Alice: Checking with John...
    Alice->John: Yes... John, how are you?
```

https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCiAgICBBbGljZSAtPj4gQm9iOiBIZWxsbyBCb2IsIGhvdyBhcmUgeW91PwogICAgQm9iLS0-PkpvaG46IEhvdyBhYm91dCB5b3UgSm9obj8KICAgIEJvYi0teCBBbGljZTogSSBhbSBnb29kIHRoYW5rcyEKICAgIEJvYi14IEpvaG46IEkgYW0gZ29vZCB0aGFua3MhCiAgICBOb3RlIHJpZ2h0IG9mIEpvaG46IEJvYiB0aGlua3MgYSBsb25nPGJyLz5sb25nIHRpbWUsIHNvIGxvbmc8YnIvPnRoYXQgdGhlIHRleHQgZG9lczxici8-bm90IGZpdCBvbiBhIHJvdy4KICAgIEJvYi0tPkFsaWNlOiBDaGVja2luZyB3aXRoIEpvaG4uLi4KICAgIEFsaWNlLT5Kb2huOiBZZXMuLi4gSm9obiwgaG93IGFyZSB5b3U_/error/dW5kZWZpbmVk

Result: undefined
![image](https://user-images.githubusercontent.com/893650/37265793-de12c956-25c6-11e8-884f-387617808a46.png)

**Comment by davojta** [comment]
version: 8.0.0-alpha.3

**Comment by tylerlong** [comment]
Fixed

**Comment by tylerlong** [comment]
Not sure why, If I click the link you post above there is still an issue.

Buu the link below is fine. And the code is identical

https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCiAgICBBbGljZSAtPj4gQm9iOiBIZWxsbyBCb2IsIGhvdyBhcmUgeW91PwogICAgQm9iLS0-PkpvaG46IEhvdyBhYm91dCB5b3UgSm9obj8KICAgIEJvYi0teCBBbGljZTogSSBhbSBnb29kIHRoYW5rcyEKICAgIEJvYi14IEpvaG46IEkgYW0gZ29vZCB0aGFua3MhCiAgICBOb3RlIHJpZ2h0IG9mIEpvaG46IEJvYiB0aGlua3MgYSBsb25nPGJyLz5sb25nIHRpbWUsIHNvIGxvbmc8YnIvPnRoYXQgdGhlIHRleHQgZG9lczxici8-bm90IGZpdCBvbiBhIHJvdy4KICAgIEJvYi0tPkFsaWNlOiBDaGVja2luZyB3aXRoIEpvaG4uLi4KICAgIEFsaWNlLT5Kb2huOiBZZXMuLi4gSm9obiwgaG93IGFyZSB5b3U_

**Comment by davojta** [comment]
@tylerlong Thank you for your work!
