### ISSUE TITLE
Stuck in building constructor.j

### ISSUE THREAD

**Issue by eugeneyp** [mermaidjs/mermaid-live-editor#22]
**Steps to reproduce:**
When I run `yarn dev`, i see the following:

```
yarn run v1.5.1
$ parcel ./index.html -d build
Server running at http://localhost:1234
∞  Building constructor.js...
``` 

It stays at building constructor.js

On the browser (Chrome), going to localhost:1234, the page does not show up. Status says waiting for localhost.

My environment:
Windows 10 64 bit
Node v8.9.4

**Comment by tylerlong** [comment]
I cannot reproduce this issue:

```
➜  mermaid-live-editor git:(master) ✗ yarn dev
yarn run v1.5.1
$ parcel ./index.html -d build
Server running at http://localhost:1234
✨  Built in 27.34s.
```

Did you run `yarn install` to update the dependencies?

If you still cannot get it work, I think you should report a bug to the Parcel project: https://github.com/parcel-bundler/parcel
