### ISSUE TITLE
Creating a new theme

### ISSUE THREAD

**Issue by kwailamchan** [mermaidjs/mermaid-live-editor#24]
Is there any way to create a new theme like default, forest, dark, neutral etc as I would like to customize my diagram in a new style?

I red the sources of View.js / Edit.js, but I did not find the css modification.

Thanks.

**Comment by kwailamchan** [comment]
Problem solved.
I found the theme modification is located at ``node_modules/mermaid/src/themes/...``

**Comment by tylerlong** [comment]
Great. Please send us a PR once you've got it done. Mermaid users will thank you :)
