### ISSUE TITLE
Word wrap for notes in Sequence Diagrams

### ISSUE THREAD

**Issue by damian-tarnawsky** [mermaidjs/mermaid-live-editor#25]
At the moment the live editor does not word wrap notes for sequence diagrams.

Here's a example to paste in:
sequenceDiagram
   participant A
   participant B 
   note left of A: All is looking great until it doesnt word wrap and my diagram looks sad :(

I love this tool and i think with this feature fixed i'd be using it all the time to design diagrams quickly and add to my high level design documents.

**Comment by tylerlong** [comment]
Currently you need to do line break manually, like this: https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5wYXJ0aWNpcGFudCBBXG5wYXJ0aWNpcGFudCBCXG5ub3RlIGxlZnQgb2YgQTogQWxsIGlzIGxvb2tpbmcgZ3JlYXQ8YnIvPiB1bnRpbCBpdCBkb2VzbnQgd29yZDxici8-IHdyYXAgYW5kIG15IDxici8-ZGlhZ3JhbSBsb29rcyBzYWQgOigiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ
