### ISSUE TITLE
Fontawesome not working

### ISSUE THREAD

**Issue by euoia** [mermaidjs/mermaid-live-editor#27]
I tried the example described in "Basic support for fontawesome" here:
https://mermaidjs.github.io/flowchart.html

But the icons do not appear to be loading for me.

**Comment by tylerlong** [comment]
fixed

https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ
