### ISSUE TITLE
SVG Scaling Issue in IE11 (and maybe others)

### ISSUE THREAD

**Issue by marcoelia** [mermaidjs/mermaid-live-editor#3]
The SVG image on IE doesn't scale.
Good stuff @tylerlong.

**Comment by tylerlong** [comment]
What do you mean by "doesn't scale"?

I don't have IE to test. I tested in other browsers and I do notice some issue.  The labels and text will be misplaced when scaling up. Not sure it's the same issue you reported.

**Comment by marcoelia** [comment]
Sorry, should have been more clear and provided an example.
Attached what the default diagram looks like on IE11 vs. Chrome on the same monitor.
On IE11 the SVG is tiny and no text is even visible.

![ie11](https://user-images.githubusercontent.com/24278104/30430727-23288a78-992a-11e7-8699-1468061809a7.png)

![chrome](https://user-images.githubusercontent.com/24278104/30430736-2abaab04-992a-11e7-9e26-b083d18478d6.png)

**Comment by tylerlong** [comment]
The IE issue is not a new issue. I guess we have to give up IE but only support Microsoft Edge.

**Comment by marcoelia** [comment]
ok thank you
