### ISSUE TITLE
What happens to the diagrams created on the live editor?

### ISSUE THREAD

**Issue by stefanocrosta** [mermaidjs/mermaid-live-editor#30]
Sorry not sure if this is the best place to ask, but:

i really like the live editor. Combined with the viewer i basically don't need anything else.
So I started creating several diagrams and just saving the url - they seem to be "unique" and "saved"; if I share the url other people can see them as well.

Which makes me wonder: 
1. what happens to those diagrams?
2. Are they stored indefinitely or do you eventually delete them?
3. Is there an api/request to see all existing ones, or once the link lost access is lost forever?

I'm not asking for (cool) features (such as login to see all of your diagrams for instance).

Just trying to understand how it currently works on mermaidjs.github.io!

Super cool project by the way, big kudos, both the "engine" and the live editor!

**Comment by tylerlong** [comment]
The diagrams are NOT stored on the server side. Actually there is no server side, the live editor is a pure static website hosted by. GitHub Pages.

The diagram is being "stored" in the url. You probably have noticed that the urls are pretty long.  So yes, once you lose the url, you also lose the diagram.

I **do** have the plan to write some server side code to store the diagrams. So you can login and view all of you diagrams.

**Comment by stefanocrosta** [comment]
Thanks @tylerlong ! 
Oh well I was wondering about the long URLs :-) That's quite smart!
I'm sure there's a market for a paid account to manage diagrams online...

But the current solution is really neat already!
