### ISSUE TITLE
Better Code Editor to Have Ability to Auto-indentation, Tabs, etc

### ISSUE THREAD

**Issue by awcodify** [mermaidjs/mermaid-live-editor#45]
For usability reason, I think we need to use a better code editor. With the current native text area, it's hard to write codes. For example for indentation, I need to manually fit the space.  It happened in my daily use of mermaid.

Can we have this ability? Or mermaid have your own opinion to not to use rich code editor? If we have no other options and you want it, then I'll create a pull request for this.

**Comment by chenzz** [comment]
Agree!!
Please support this~~

**Comment by hikerpig** [comment]
Maybe [CodeMirror](https://codemirror.net) would be a good start ?
