### ISSUE TITLE
Where can I find other build-in theme?

### ISSUE THREAD

**Issue by 9468305** [mermaidjs/mermaid-live-editor#49]
Hi guys:

I saw `default` theme in `https://mermaidjs.github.io/mermaid-live-editor`. So I guess there are more build-in themes ?
But I didn't found out any related documents. Could you tell me any links about it? Thanks

**Comment by Haroenv** [comment]
The other themes are: default, forest, dark or neutral

I found this in the cli: https://github.com/mermaidjs/mermaid.cli#options

**Comment by Haroenv** [comment]
https://github.com/knsv/mermaid/tree/master/src/themes

**Comment by 9468305** [comment]
Awesome! Thanks.
