### ISSUE TITLE
Is there a Dockerfile Available for the Editor?

### ISSUE THREAD

**Issue by psychemedia** [mermaidjs/mermaid-live-editor#8]
Hi

Is there an official Docker image or Dockerfile available for running the editor in a Docker container?

--tony

**Comment by tylerlong** [comment]
Nope there isn't.

This built project is a pure static website. You can just download the source code and open the index.html file to execute it.  Or you can host the code with apache/nginx/IIS ...etc.

I will leave it to the community to create a Dockerfile because I don't use docker myself.

**Comment by psychemedia** [comment]
Ah -ok - thanks - I misunderstood how it worked when I saw a server launching.

**Comment by tylerlong** [comment]
The server is for development only. For production,  no server needed. Pure client side.
